# Generated by Django 5.2.1 on 2026-07-14 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_records/', verbose_name='녹음 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_records', to='bible.verse', verbose_name='구절')),
            ],
            options={
                'verbose_name': '음성 녹음',
                'verbose_name_plural': '음성 녹음 목록',
                'ordering': ['verse__book__order', 'verse__chapter__number', 'verse__number'],
            },
        ),
    ]
