# Generated by Django 3.2.25 on 2026-05-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='책이름')),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2, verbose_name='구약/신약')),
                ('order', models.IntegerField(verbose_name='순서')),
            ],
            options={
                'verbose_name': '성경',
                'verbose_name_plural': '성경 목록',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='장 번호')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bible.book')),
            ],
            options={
                'verbose_name': '장',
                'verbose_name_plural': '장 목록',
                'ordering': ['book__order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='절 번호')),
                ('text', models.TextField(verbose_name='내용')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.chapter')),
            ],
            options={
                'verbose_name': '절',
                'verbose_name_plural': '절 목록',
                'ordering': ['book__order', 'chapter__number', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['book', 'chapter', 'number'], name='bible_verse_book_id_704d3f_idx'),
        ),
    ]
